--- # webserver setup
- hosts: server2.abc.com
  user: ricky
  sudo: yes
  tasks:
  - name: restart httpd service 
    service: name=httpd state=started
  - name: update httpd service
    yum: name=httpd state=updated
